package com.muhammadsayed.design.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00576E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF007F9F)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF426370)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC7E9F9)
val onSecondaryContainerLight = Color(0xFF2C4D5A)
val tertiaryLight = Color(0xFF6A3E7F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9162A7)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FAFD)
val onBackgroundLight = Color(0xFF181C1E)
val surfaceLight = Color(0xFFF6FAFD)
val onSurfaceLight = Color(0xFF181C1E)
val surfaceVariantLight = Color(0xFFDAE4EA)
val onSurfaceVariantLight = Color(0xFF3E484D)
val outlineLight = Color(0xFF6E797E)
val outlineVariantLight = Color(0xFFBEC8CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3133)
val inverseOnSurfaceLight = Color(0xFFEEF1F4)
val inversePrimaryLight = Color(0xFF74D2F6)
val surfaceDimLight = Color(0xFFD7DADD)
val surfaceBrightLight = Color(0xFFF6FAFD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F7)
val surfaceContainerLight = Color(0xFFEBEEF1)
val surfaceContainerHighLight = Color(0xFFE5E9EB)
val surfaceContainerHighestLight = Color(0xFFDFE3E6)

val primaryDark = Color(0xFF74D2F6)
val onPrimaryDark = Color(0xFF003544)
val primaryContainerDark = Color(0xFF007A98)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFAACCDB)
val onSecondaryDark = Color(0xFF113441)
val secondaryContainerDark = Color(0xFF20424E)
val onSecondaryContainerDark = Color(0xFFB4D6E6)
val tertiaryDark = Color(0xFFE8B3FF)
val onTertiaryDark = Color(0xFF471C5D)
val tertiaryContainerDark = Color(0xFF8C5EA2)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101416)
val onBackgroundDark = Color(0xFFDFE3E6)
val surfaceDark = Color(0xFF101416)
val onSurfaceDark = Color(0xFFDFE3E6)
val surfaceVariantDark = Color(0xFF3E484D)
val onSurfaceVariantDark = Color(0xFFBEC8CE)
val outlineDark = Color(0xFF889298)
val outlineVariantDark = Color(0xFF3E484D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE3E6)
val inverseOnSurfaceDark = Color(0xFF2D3133)
val inversePrimaryDark = Color(0xFF006781)
val surfaceDimDark = Color(0xFF101416)
val surfaceBrightDark = Color(0xFF353A3C)
val surfaceContainerLowestDark = Color(0xFF0A0F11)
val surfaceContainerLowDark = Color(0xFF181C1E)
val surfaceContainerDark = Color(0xFF1C2022)
val surfaceContainerHighDark = Color(0xFF262B2D)
val surfaceContainerHighestDark = Color(0xFF313538)






